spring:
  application:
    name: pcs-gateway-integration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop  # When you launch the application for the first time - switch "none" at "create"

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true